version: "3"
# common commands:

# docker system prune -f --volumes
# Restart a container or scale
#docker-compose up -d --scale product=0
#docker-compose up -d --scale product=1
services:
  product:
    build: services/product-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices

  recommendation:
    build: services/recomendation-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices

  review:
    build: services/review-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices

  product-composite:
    build: services/product-composite-service
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
