server.port: 7001
server.error.include-message: always

# Event-Driver configuration
spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
# Fin

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

logging:
  level:
    root: INFO
    com.book.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

# When we use yml we can separate different profile by adding
# `---`
# that means when we run our application with profile 'docker' it will overwrite previous one
# server.port: 7001
---
spring.profiles: docker

spring.data.mongodb.host: mongodb
server.port: 8080
spring.rabbitmq.host: rabbitmq
spring.cloud.stream.kafka.binder.brokers: kafka
# We are passing this properties directly from composer files
#spring:
#  cloud:
#    stream:
#      kafka:
#        binder:
#          autoAddPartitions: true
#          minPartitionCount: 4
#          replicationFactor: 1
