server.port: 7001
server.error.include-message: always


spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

logging:
  level:
    root: INFO
    com.book.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

# When we use yml we can separate different profile by adding
# `---`
# that means when we run our application with profile 'docker' it will overwrite previous one
# server.port: 7001
---
spring.profiles: docker
server.port: 8080
